
package webServices.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "KeyAlreadyPresentException", targetNamespace = "http://webServices/")
public class KeyAlreadyPresentException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private KeyAlreadyPresentException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public KeyAlreadyPresentException_Exception(String message, KeyAlreadyPresentException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public KeyAlreadyPresentException_Exception(String message, KeyAlreadyPresentException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webServices.client.KeyAlreadyPresentException
     */
    public KeyAlreadyPresentException getFaultInfo() {
        return faultInfo;
    }

}
