
package webServices.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KVBServer", targetNamespace = "http://webServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KVBServer {


    /**
     * 
     * @param arg0
     * @throws ServiceAlreadyInitializedException_Exception
     * @throws ServiceInitializingException_Exception
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://webServices/", className = "webServices.client.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://webServices/", className = "webServices.client.InitResponse")
    @Action(input = "http://webServices/KVBServer/initRequest", output = "http://webServices/KVBServer/initResponse", fault = {
        @FaultAction(className = ServiceAlreadyInitializedException_Exception.class, value = "http://webServices/KVBServer/init/Fault/ServiceAlreadyInitializedException"),
        @FaultAction(className = ServiceInitializingException_Exception.class, value = "http://webServices/KVBServer/init/Fault/ServiceInitializingException"),
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://webServices/KVBServer/init/Fault/FileNotFoundException")
    })
    public void init(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws FileNotFoundException_Exception, ServiceAlreadyInitializedException_Exception, ServiceInitializingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws ServiceNotInitializedException_Exception
     * @throws KeyNotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://webServices/", className = "webServices.client.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://webServices/", className = "webServices.client.DeleteResponse")
    @Action(input = "http://webServices/KVBServer/deleteRequest", output = "http://webServices/KVBServer/deleteResponse", fault = {
        @FaultAction(className = KeyNotFoundException_Exception.class, value = "http://webServices/KVBServer/delete/Fault/KeyNotFoundException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://webServices/KVBServer/delete/Fault/ServiceNotInitializedException")
    })
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0)
        throws KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ServiceNotInitializedException_Exception
     * @throws KeyAlreadyPresentException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "insert", targetNamespace = "http://webServices/", className = "webServices.client.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://webServices/", className = "webServices.client.InsertResponse")
    @Action(input = "http://webServices/KVBServer/insertRequest", output = "http://webServices/KVBServer/insertResponse", fault = {
        @FaultAction(className = KeyAlreadyPresentException_Exception.class, value = "http://webServices/KVBServer/insert/Fault/KeyAlreadyPresentException"),
        @FaultAction(className = IOException_Exception.class, value = "http://webServices/KVBServer/insert/Fault/IOException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://webServices/KVBServer/insert/Fault/ServiceNotInitializedException")
    })
    public void insert(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ValueListImpl arg1)
        throws IOException_Exception, KeyAlreadyPresentException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ServiceNotInitializedException_Exception
     * @throws IOException_Exception
     * @throws KeyNotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://webServices/", className = "webServices.client.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://webServices/", className = "webServices.client.UpdateResponse")
    @Action(input = "http://webServices/KVBServer/updateRequest", output = "http://webServices/KVBServer/updateResponse", fault = {
        @FaultAction(className = KeyNotFoundException_Exception.class, value = "http://webServices/KVBServer/update/Fault/KeyNotFoundException"),
        @FaultAction(className = IOException_Exception.class, value = "http://webServices/KVBServer/update/Fault/IOException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://webServices/KVBServer/update/Fault/ServiceNotInitializedException")
    })
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ValueListImpl arg1)
        throws IOException_Exception, KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webServices.client.ValueListImpl
     * @throws ServiceNotInitializedException_Exception
     * @throws IOException_Exception
     * @throws KeyNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://webServices/", className = "webServices.client.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://webServices/", className = "webServices.client.ReadResponse")
    @Action(input = "http://webServices/KVBServer/readRequest", output = "http://webServices/KVBServer/readResponse", fault = {
        @FaultAction(className = KeyNotFoundException_Exception.class, value = "http://webServices/KVBServer/read/Fault/KeyNotFoundException"),
        @FaultAction(className = IOException_Exception.class, value = "http://webServices/KVBServer/read/Fault/IOException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://webServices/KVBServer/read/Fault/ServiceNotInitializedException")
    })
    public ValueListImpl read(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0)
        throws IOException_Exception, KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<webServices.client.ValueListImpl>
     * @throws ServiceNotInitializedException_Exception
     * @throws BeginGreaterThanEndException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "scan", targetNamespace = "http://webServices/", className = "webServices.client.Scan")
    @ResponseWrapper(localName = "scanResponse", targetNamespace = "http://webServices/", className = "webServices.client.ScanResponse")
    @Action(input = "http://webServices/KVBServer/scanRequest", output = "http://webServices/KVBServer/scanResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://webServices/KVBServer/scan/Fault/IOException"),
        @FaultAction(className = BeginGreaterThanEndException_Exception.class, value = "http://webServices/KVBServer/scan/Fault/BeginGreaterThanEndException"),
        @FaultAction(className = ServiceNotInitializedException_Exception.class, value = "http://webServices/KVBServer/scan/Fault/ServiceNotInitializedException")
    })
    public List<ValueListImpl> scan(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        KeyImpl arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Predicate arg2)
        throws BeginGreaterThanEndException_Exception, IOException_Exception, ServiceNotInitializedException_Exception
    ;

}
